<?php

namespace WeCreaBundle\Repository;

/**
 * ActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuRepository extends \Doctrine\ORM\EntityRepository
{
}
