<?php

namespace WeCreaBundle\Repository;

/**
 * CaractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaractRepository extends \Doctrine\ORM\EntityRepository
{
}
