<?php

namespace WeCreaBundle\Repository;

/**
 * ConceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get conecpt page for edit
     * @return mixed
     */
    public function getConceptPage(){
        return $this->createQueryBuilder('c')->getQuery()->getSingleResult();
    }
}
