<?php

namespace WeCreaBundle\Repository;

/**
 * LegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get text defiscalisation
	 * @return mixed
	 */
	public function getFooter()
	{
		return $this->createQueryBuilder('l')
			->select('l.defiscalisation', 'l.cgu', 'l.mention', 'l.facebook', 'l.instagram', 'l.tva', 'l.twitter', 'l.youtube')
			->getQuery()
			->getSingleResult();
	}

	/**
	 * @return mixed
	 */
	public function getCGV()
	{
		return $this->createQueryBuilder('l')
			->select('l.cgv')
			->getQuery()
			->getSingleScalarResult();
	}

	/**
	 * @return mixed
	 */
	public function getReturnWorkText(){
		return $this->createQueryBuilder('l')
			->select('l.returnWorkText')
			->getQuery()
			->getSingleScalarResult();
	}
}
