<?php

namespace WeCreaBundle\Repository;

/**
 * LegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get text defiscalisation
	 * @return mixed
	 */
	public function getDefiscalisation()
	{
		return $this->createQueryBuilder('l')
			->select('l.defiscalisation')
			->getQuery()
			->getSingleScalarResult();
	}
}
