<?php

namespace WeCreaBundle\Repository;

/**
 * NatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get nature name, picture and fontColor
	 * @return array
	 */
	public function getNatureName()
	{
		$qb = $this->createQueryBuilder('n');
		$qb->select('n.name as name', 'n.fontColor as fontColor')
			->join('n.images', 'i')
			->addSelect('i.url as image_url');
		return $qb->getQuery()->getResult();
	}
}
