<?php

namespace WeCreaBundle\Repository;

/**
 * NatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureRepository extends \Doctrine\ORM\EntityRepository
{
}
