<?php

namespace WeCreaBundle\Repository;

/**
 * SentMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
