<?php

namespace WeCreaBundle\Repository;

/**
 * WorkPurchasedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkPurchasedRepository extends \Doctrine\ORM\EntityRepository
{
}
