WeCreaBundle\Entity\Legal:
    type: entity
    table: null
    repositoryClass: WeCreaBundle\Repository\LegalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mention:
            type: text
        tva:
            type: float
        defiscalisation:
            type: text
        cgv:
            type: text
        cgu:
            type: text
        facebook:
            type: string
            length: 255
            nullable: true
        twitter:
            type: string
            length: 255
            nullable: true
        instagram:
            type: string
            length: 255
            nullable: true
        youtube:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 14
            nullable: true
        returnWorkText:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
