WeCreaBundle\Entity\Newsletter:
    type: entity
    table: null
    repositoryClass: WeCreaBundle\Repository\NewsletterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime

